[ui.sound]
enabled = false

[keys]
switch_tab = "alt+1..9"
new_tab = "alt+t"
next_tab = "alt+f"
previous_tab = "alt+s"
detach = "alt+d"
move_tab_previous = "alt+["
move_tab_next = "alt+]"
rename_tab = "alt+n"
rename_workspace = "alt+shift+n"
goto = "alt+e"
toggle_sidebar = "alt+shift+e"

