litellm_settings:
  drop_params: true

model_list:
  - model_name: gpt-*
    litellm_params:
       model: github_copilot/gpt-*

  - model_name: gemini-*
    litellm_params:
       model: github_copilot/gemini-*

  - model_name: claude-opus-4-*
    litellm_params:
      model: github_copilot/claude-opus-4.*

  - model_name: claude-sonnet-4-*
    litellm_params:
      model: github_copilot/claude-sonnet-4.*

  - model_name: claude-haiku-4-*
    litellm_params:
      model: github_copilot/claude-haiku-4.*
